[package]
name = "crafting-interpreters"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
insta = "1.39.0"
itertools = "0.13.0"
once_cell = "1.19.0"

[lints.clippy]
needless_lifetimes = "allow"
len_zero = "allow"
type_complexity = "allow"
manual_range_contains = "allow"
